version: '3.7'
services:
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/usr/src/el_royale/
    ports:
      - 8000:8000
    depends_on:
      - db
  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=beliar
      - POSTGRES_PASSWORD=beliar_db_password
      - POSTGRES_DB=el_royale
volumes:
  postgres_data: